cfgmgmtcamp/cfgmgmtcamp.github.io

chef.html, page_template.html
Also adds a page template for others to use.
=> Fix chef headers

index.html, puppet.html
Added page for Puppet room. Added Chef and Puppet rooms to the about section of the main page to make them easier to find
=> Added Puppet page and added links from main page to Puppet and Chef pages

page_template.html
As a marketing guy with some HTML and GitHub experience, I hope I'm doing this right. Sorry in advance if I'm not. This is the content and consolidated agenda for the SaltStack community room to be posted to cfgmgmtcamp.eu/salt 
It is based on the code from the Chef page (thank you btw).
=> SaltStack community room

Chef/lightning.html, Chef/paciorkowska.html, Chef/paulus.html, Chef/zts.html, chef.html
More details for the Chef talks.  I'll add these to Lanyard, too.
=> Fill chef tbd slots

Chef/paulus.html
On request of @nathenharvey this PR updates the description for my lighting talk and bio.
As a bonus change I've included Font Awesome for the social icons. If you like it, I can add it to all the chef pages and extend this PR. If you don't I'll update the pull request and remove it.
=> [Chef] [Feedback] Updating lighting talk and bio description

Chef/paciorkowska.html, Chef/zts.html
This PR adds the social icons where details are available.
/cc: @nathenharvey
=> Add Font Awseome social icons where social details are available

rudder-cfengine.html
Update talk titles in Rudder - CFEngine room
=> Talk titles update

Chef/ama.html, Chef/dunn.html, Chef/goetz.html, Chef/keiser.html, Chef/lightning.html, Chef/miranda.html, Chef/omeara.html, Chef/paciorkowska.html, Chef/paulus.html, Chef/zts.html, page_template.html
* Add links to twitter and github
* Add speaker, date, time, and location to the chef pages
* Fix link to favicon
=> Social chefs

Chef/ama.html, Chef/dunn.html, Chef/goetz.html, Chef/keiser.html, Chef/lightning.html, Chef/miranda.html, Chef/omeara.html, Chef/paciorkowska.html, Chef/paulus.html, Chef/zts.html, Social.html, Venue.html, chef.html, code_of_conduct.html, index.html, page_template.html, puppet.html, rudder-cfengine.html, salt.html
=> Code of conduct

puppet.html
=> added link to Morgan's slides

index.html
Also Improved consistency in the language used.
=> cleaned up some punctuation / grammar. 

code_of_conduct.html, index.html, page_template.html
A minimal change to bump dates to 2016 and update days to 1, 2 Feb instead of 2,3.
=> bumps year in title to 2016 and updates 2,3 Feb to 1,2 Feb

index.html
- Added Icinga (Netways) as sponsor
- Changed intendation for all silver sponsors so code looks nicer
=> Icinga / indendation

schedule/chef/johnson.html
put it in the same place as other bio pics.
=> Move Kimball's picture

index.html
Please add us as bronze sponsor. Thanks!
=> added atcomputing as a bronze sponsor

schedule/cfengine-rudder/messaging.html, schedule/cfengine-rudder/roadshow.html, schedule/index.html
Messaging CFEngine and Data
The CFEngine Roadshow BYOVM
=> Add: Martin Simons Sessions

schedule/index.html
=> rename talk Cfg Mgmt vs. Containers

ksp.html
Paging @nibalizer for a verification of the content and suggested procedure.
=> Add a page on the upcoming key signing party

schedule/index.html
Ori will be giving the talk with me.
=> Add Ori Rabin to Foreman parameter talk

schedule/speakers/IgorAndDavid.html
there is never enough code review.
=> Fix typos, time, and location

schedule/index.html, schedule/speakers/PeterSouter.html
=> Fixes links for my talk

schedule/index.html, schedule/speakers/EricSorenson.html
- updated schedule index
- added bio page
=> Update puppet room to replace Henriks talk with mine

schedule/index.html, schedule/speakers/BrianExelbierd.html
Updating speaker from @vpavlin to @bexelbie - do you want originally scheduled speakers noted in a different manner?  Other than showing up for the talk should/could I do other things?
=> Update Nulecule Talk Speaker

schedule/speakers/OriRabin.html, schedule/speakers/TomerBrisker.html
Also, a correction to my bio which was taken from a different lecture
proposal.
=> Lecture got cut in half. There goes the demo.

schedule/index.html, schedule/speakers/JamesShubin.html, schedule/speakers/PaulStack.html
Kris: please verify I got the schedule right and can you update the lanyard thing please?
Hope this patch makes your life easier!
=> @purpleidea's talk switched to main track

schedule/index.html
=> Fix Ansible typo

schedule/speakers/CraigDunn.html
These are the slides from my talk on Jerakia in the Puppet track.....
=> added slideshare for Jerakia talk

schedule/speakers/ArnoldBechtoldt.html, schedule/speakers/ArnoldandJohannes.html
=> add slideshare links

2015/rudder-cfengine.html, schedule/cfengine-rudder/ncf.html, schedule/cfengine-rudder/rudder-mission-portal.html
talks in the CFEngine Rudder room (apparently I forgot this...)
=> Add slides for one talk in 2016 and add all links to videos from 2015

schedule/index.html
More coming and in higher quality, but this is a start.
=> Add videos and slides

berlin-2016/index.html, gent-2017/index.html
Fix a header link and make some other grammar and copy changes.
=> Minor updates for Berlin

berlin-2016/index.html, gent-2017/index.html, index.html, past_events.html
Simplifies the nav bar on other pages.
Easier to navigate the site.
=> One page to link to all past events

berlin-2016/index.html, berlin-2016/talks.html
This way Felix won't have to spend half of his ignite providing context
for Mgmt
=> Let's switch me and @purpleidea

berlin-2016/index.html, berlin-2016/talks.html
Filling in the blanks so people know what I'm going to talk about :-)
Also, is Cyrill von Wattenwyl still on the schedule?  His content is in talks.html, but not on the main schedule.
=> Adding details about myself to schedule and talks

berlin-2016/talks.html
Linking to my slides. Also took the liberty to amend my bio (marketing had asked me to add this.)
=> Slides felix

berlin-2016/talks.html
As you kindly asked this pull request provides a link to my slides.
=> adds link to slides for dgoetz

berlin-2016/talks.html
Here's a link to my slides from the event.
=> talks: purpleidea: Add slides

berlin-2016/talks.html
=> Add link to Nathen Harvey's Habitat talk

index.html
Remove notice that it is closed from the home page
=> The CFP has been closed long enough.

index.html
Removes the section about important deadlines
=> The most important deadlines have past

fringe.html, index.html
Cleans up some of the formatting, too.
=> add Habitat workshop to Fringe page

index.html
It should be "make" not "m
ake"
=> Fixes a typo

fringe.html, index.html, schedule/chef.html, schedule/containers/ian-henry.html, schedule/index.html
* Link to the schedule from the home page
* Add more information about the fringe events to the schedule page
* Add the Habitat workshop to the Chef schedule page
* Add the Chef Code of Conduct to the Habitat page
=> Schedule updates

schedule/chef/stuart-preston.html
Updating bio. /cc @nathenharvey
=> Changing Stuart Preston bio to reflect current position at Chef

fringe.html
I'll be around, and so long as nobody minds, I'm going to add this to
the fringe section.
=> fringe: Add casual mgmt hackathon

fringe.html, schedule/chef.html
=> Add links to register for the Habitat Workshop

schedule/chef/marek-hulan.html, schedule/foreman/daniel-lobato-garcia.html, schedule/foreman/greg-sutcliffe.html, schedule/foreman/lukas-zapletal.html, schedule/foreman/michael-moll.html, schedule/foreman/ohad-levy.html, schedule/foreman/rich-jerrido.html, schedule/foreman/simon-peeters.html, schedule/foreman/tomas-strachota.html, schedule/foreman/tomer-brisker.html, schedule/index.html
I merged Marek's Foreman talk to the chef page for him, since the page title is for the *speaker*. Can split it if you prefer.
=> Add Foreman talks & speaker links/bios

schedule/misc/justin-carter.html
Fix typo and add speaker png for justin-carter
=> Add justin.png

schedule/puppet/felix-frank.html
Gotta harvest that additional nerd cred ;)
Also our marketing manager is all about these hyper-links...I guess they spent too much time around SEO folks.
=> update Felix' CV and link to his employer

schedule/index.html, schedule/juju/alex-and-liam.html, schedule/juju/charles-butler.html, schedule/juju/james-page.html, schedule/juju/jorge-and-marco.html, schedule/juju/kevin-monroe.html, schedule/juju/kons-tsakalozos.html, schedule/juju/matthew-bruzek.html, schedule/juju/tim-van-steenburgh.html
=> Add Juju track schedule.

schedule/index.html
Align the case for Break and Lunch of "Future Tooling" to match the other tracks.
=> Align the case

schedule/index.html
not sure we need separate pages with bios etc...but let me know
=> draft Kubernetes schedule

schedule/index.html
I'm parsing the schedule for use with the [Giggity schedule viewer](https://play.google.com/store/apps/details?id=net.gaast.giggity), these small fixes make the world a better place ;)
=> Some small fixes

schedule/ignites.html
=> add some formatting / punctuations

schedule/ignites.html
I hope this is still valid html
I really really tried!
=> add florians ignite

schedule/index.html, schedule/juju/james-page.html
=> charms: flexible openstack deployment

fringe.html
=> Updated room numbers fringe events

schedule/juju/alex-and-liam.html
The Juju "writing better charms" workshop will works better if attendees have pre-installed a dev/test environment.  This PR adds to the alex-and-liam.html shedule page.
=> Added 'before you arrive' to alex-and-liam Juju workshop

schedule/index.html
Some more small changes to allow me to parse the HTML. Be aware that this kind of changes the titles of a handful of talks (' -' becomes ':'). Doesn't affect links or anything else.
=> parseability changes

schedule/puppet/peter-souter.html
* Talk has been changed to be more Puppet focused
from FOSDEM talk
=> Refactoring from FOSDEM base

schedule/index.html
=> minor fixes

schedule/chef/steffen-gebert.html
Few pointers to the things I'm referring to.
@nathenharvey
=> Schedule/Chef/Steffen-Gebert: Add links

schedule/future/james-shubin.html, schedule/index.html
We'll be covering some advanced/new material in a talk format at the
start.
=> schedule: Be more specific

schedule/ignites.html
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Add the slides "Ignite talk about Vox Pupuli"

schedule/puppet/julien-pivotto.html
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Add the slides "Puppet DSL: back to the basics"

schedule/ansible/dag-wieers.html, schedule/index.html
=> Update schedule with new Ansible talk and discussion session

schedule/index.html
Fixed broken link introduced in PR #286.
=> Fix broken link

schedule/chef/marek-hulan.html
=> Add link to Marek Hulán's slides

schedule/chef/stuart-preston.html
=> Add Stuart Preston's presentation

schedule/main/john-vincent.html
=> Add @lusis's slides

fringe.html, schedule/chef/marek-hulan.html, schedule/chef/michael-goetz.html, schedule/chef/stuart-preston.html, schedule/chef/thom-may.html, schedule/containers/michael-ducy.html, schedule/future/julian-dunn.html, schedule/main/annie-hedgpeth.html, schedule/main/gareth-rushgrove.html, schedule/main/george-miranda.html, schedule/main/hannah-foxwell.html
=> Add more slides, clean-up the display a bit

schedule/chef/tim-smith.html
=> Link to @tas50's slides

index.html
Typo in devopsdays; also the CFP is closed and schedule posted so "CFP coming soon" is not true :)
=> Update header info about cfgmgmtcamp PDX

fringe.html
I'm just assuming for Puppet, Chef and Foreman, but mgmtconfig would
like to come back, so I figured I'd update this for everyone.
Uninterested users should send a patch after this is merged, or ping so
that I fix this before merging.
=> fringe: Update fringe page for 2018

index.html
Update the registration information on the home page
=> Ticket sales are now available!

code_of_conduct.html, fringe.html, index.html, past_events.html
* CFP is removed from top nav
* Fringe is added to top nav
* News item added for Fringe events
=> Highlight Fringe, De-emphasize CFP

schedule/chef.html, schedule/chef/salim-afiune.html, schedule/index.html
* Spell his last name correctly
* New title for the talk
=> Updates for Salim Afiune

index.html
It's 2018 this year. Happy new year
=> Fix year for thanking sponsers

schedule/index.html
=> Some schedule page clean-up

schedule/chef.html, schedule/index.html, schedule/k8s/ian-henry.html
=> Move Ian Henry's talk to the k8s room

schedule/index.html
Two typos and a broken anchor are fixed
=> schedule fixes

schedule/index.html, schedule/main/NextGenerationConfigMgmtTheLanguage.html, schedule/mgmt/mgmt.html
I also removed ec2 from my 2nd talk b/c Jonathan is going to be doing a
whole session on this and I have lots of material.
=> misc fixes for clarity

schedule/index.html, schedule/rudder/best-practices.html, schedule/rudder/embedded.html, schedule/rudder/scaling.html, schedule/rudder/whatsnew.html
=> Add Rudder talks

fringe.html
This had been lost on the mailing list. Rewrote style to match with the others.
=> Update: Add the cfengine hackathon

schedule/foreman/ha.html, schedule/index.html
Sorry, had a typo in the other one.
=> Second try fixing HA Foreman title

fringe.html
Adding links so our marketing people get the SEO boost (and attendees can learn more about Sysdig).
=> Add links for Sysdig on fringe page

schedule/chef.html, schedule/index.html, schedule/k8s/ian-henry.html
Signed-off-by: Ian Henry <ihenry@chef.io>
=> Updated talk content after evolution of study

food.html
Minor PR correcting a bunch of typos in the food page.
=> Food typos

food.html, schedule/index.html
Signed-off-by: Stuart Preston <stuart@chef.io>
=> Fixing a few typos, standardize on en-US

schedule/ansible/cisco.html, schedule/ansible/icinga.html, schedule/ansible/introduction.html, schedule/ansible/magic.html, schedule/ansible/molecule.html, schedule/ansible/nathen-harvey.html, schedule/ansible/notpuppet.html, schedule/ansible/windows.html, schedule/rudder/best-practices.html, schedule/rudder/embedded.html, schedule/rudder/legacy.html, schedule/rudder/scaling.html, schedule/rudder/whatsnew.html, schedule/salt/monitoring.html
- added social network information for Ansible speakers
- fixed salt class typo
=> Social network information for Ansible speakers

schedule/chef.html
=> Update the title on the Chef page, too

schedule/ansible/nathen-harvey.html, schedule/chef.html, schedule/chef/ama.html, schedule/chef/anton-melser.html, schedule/chef/heike-hallenberger.html, schedule/chef/salim-afiune.html, schedule/chef/stuart-preston.html, schedule/chef/thom-may.html, schedule/chef/tim-smith.html, schedule/k8s/ian-henry.html
=> Add room numbers to Chef talks

schedule/index.html
- Swap Distributed firewall and State of CFEngine talks so that it
better flows into open conversation.
- Swap Break and Martin Simons Role based configuration talk so as not
to conflict with Marco Maronguis talk on managing teams with  Promise
Theory.
=> Suffle CFEngine Schedule

schedule/chef.html, schedule/chef/sean-omeara.html, schedule/index.html
He has requested the talk description be a bit more vague.
=> Updates to @someara's talk

schedule/chef.html, schedule/chef/tim-smith.html, schedule/index.html
His Chef 14 talk will now be Monday and Containers on Tuesday
=> Switch around the talks from Tim Smith

schedule/terraform/funprofit.html
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> update my name again

schedule/chef/tim-smith.html
=> Move the in-page anchors

schedule/index.html
MISC was removed with room swap
=> add misc back

schedule/chef.html, schedule/index.html, schedule/main/adam-jacob.html
=> Adam Jacob will speak in Ian Henry's place

fringe.html, schedule/chef.html
=> Add fringe rooms

schedule/chef.html, schedule/main/adam-jacob.html
=> Update location of Adam's talk

fringe.html, schedule/chef.html
=> Move the Chef fringe room to a room with power

schedule/main/Promisetheoryfromconfigurationmanagementtoteamleadership.html
I used SpeakerDeck's embed function, so the slides will appear directly
in the page. If that's not OK let me know and I'll replace it with a link.
=> Added slides for Marco Marongiu's talk

schedule/chef/stuart-preston.html
Signed-off-by: Stuart Preston <stuart@chef.io>
=> Adding slides for Stuart Preston talk

schedule/foreman/consultant.html, schedule/foreman/monitoring.html
=> dgoetz slides

schedule/foreman/baremetal.html
I'm no HTML star, but I think this will do.
=> add slides link to baremetal.html

schedule/main/MakingImmutableInfrastructuresimplerwithLinuxKi.html
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
=> Add slides link
